# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xlbj3PSnodVh0REciPMOnNJB1kaZIe55
"""

import pandas as pd
baza= {
    "FISH":["Qadamova Zulayho","Meliboyeva Asaloy"," Aliyeva Gulsanam",
            "Xalilov Durbek","Jabborov Avazbek","Meliboyeva Dilbaroy"],
    "Manzili":["Farg'ona Shahar","Andijon Viloyati", "Namangan shahri","Farg'ona Shahar",
               "Andijon shahri","Andijon Viloyati"],
    "Yoshi": ["28","26","27","68","58","19"],
    " Ish joyi" : ["TATUFF","APTEKA","MAKTAB","TATUFF","O'QUV MARKAZ","BANK"],
    "Jinsi": ["ayol","ayol","ayol","erkak","erkak","ayol"],


}
db=pd.DataFrame(baza)
print(db)



filtr=db[db['Jinsi']=="ayol"]
print(filtr)